"""init alembic

Revision ID: c9fd0d4387f1
Revises: 
Create Date: 2024-08-22 10:51:47.168603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fd0d4387f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_info',
    sa.Column('seq_board', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=9000), nullable=True),
    sa.Column('plain_text', sa.String(length=3000), nullable=True),
    sa.Column('yn_use', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('pwd', sa.String(length=255), nullable=True),
    sa.Column('dt_create', sa.DateTime(), nullable=False),
    sa.Column('dt_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('seq_board')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_info')
    # ### end Alembic commands ###
